### PR TITLE
test: Also setup keyfile for mock-insights

### PR DESCRIPTION
**Pull request by marusak**
Otherwise `mock-insights` failed to start with SSL error.

This first needs https://github.com/cockpit-project/bots/pull/2397 to land and then I'll trigger tests here.

### CODE REVIEW

File: integration-tests/run [hunk 1]
```diff
@@ -17,7 +17,7 @@
 # for more information about the Cockpit integration test machinery.
 
 ifeq ($(TEST_OS),)
-TEST_OS = rhel-8-3
+TEST_OS = rhel-8-5
```
Comment (ptoscano) [inline integration-tests/run:20]: I'd not change this as part of the changes, as it might conflict when backported later on.

**Review by ptoscano — COMMENTED** [review]
It seems mostly OK from my (noob) POV; do you know why rhel-8-4 fails?

**Comment by marusak** [comment]
```
from insights import package_info
ModuleNotFoundError: No module named 'insights'
```

I haven't see this locally - @ptoscano do you happen to know what might be needed?

**Comment by ptoscano** [comment]
> ```
> from insights import package_info
> ModuleNotFoundError: No module named 'insights'
> ```
> 
> I haven't see this locally - @ptoscano do you happen to know what might be needed?

Hmm sorry, it doesn't ring a bell, and `insights-client` in RHEL provides a different Python module (`insights_client`).

Since the rhel-8-5 image seems to work, what about comparing rhel-8-4 and rhel-8-5 for installed packages/bits?

**Comment by marusak** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/insights_client/run.py", line 4, in <module>
    from insights import package_info
ModuleNotFoundError: No module named 'insights'
```

I havn;t noticed any missing package on rhel-9. Could please someone from this team take a look? Thanks!

**Comment by ptoscano** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/insights_client/run.py", line 4, in <module>
>     from insights import package_info
> ModuleNotFoundError: No module named 'insights'
> ```
> 
> I havn;t noticed any missing package on rhel-9. Could please someone from this team take a look? Thanks!

That seems like a broken `insights-client` package... :-/ I'll need to check with the Insights team, as it is outside our control.

**Comment by marusak** [comment]
> That seems like a broken insights-client package... :-/ I'll need to check with the Insights team, as it is outside our control.

Oh, I somehow assumed you are the same team :) I'll try to find reproducer and report it then

File: integration-tests/vm.install [hunk 2]
```diff
@@ -14,7 +14,7 @@ tar xzf ../subscription-manager-build-extra.tar.gz
 python3 ./setup.py build
 python3 ./setup.py install --prefix /usr
 
-mv /usr/bin/{rhsm-facts-service,rhsm-service,rhsmcertd-worker} /usr/libexec
```
Comment (ptoscano) [inline integration-tests/vm.install:17]: Unfortunately this won't work: sadly the current buildsystem has a mixture of `setup.py` & `Makefile` bits, so only using `setup.py` does not install everything. (In case you wonder: yes, we know about this, and we would like to fix this somewhen in the future.)

A possible alternative to simplify this would be to switch from `setup.py` to `Makefile` for build and installation. It could be a good idea for this script; I'd do it as separate work/PR though, mostly to not overload this, and to not have you fall into the rabbit hole of our buildsystem.

Comment (marusak) [reply integration-tests/vm.install:17]: Thanks for explanation. I was just curious how it is gonna fail when I remove this. And it seems it worked without it just fine :)

**Comment by ptoscano** [comment]
@marusak hmm, no rhel-8-4 image test?

**Comment by marusak** [comment]
> hmm, no rhel-8-4 image test?

I triggered `rhel-9-0` too quickly, so then no default context was triggered (this is known behavior from bots). Since I am just trying to get some info from CI, I would not worry about it :)

**Comment by jirihnidek** [comment]
@marusak Some cockpit tests are still failing. Is it expected behavior? Do you want to fix it in another PR?

**Comment by jirihnidek** [comment]
Stylish test is failing for strange reason (rpmlint). I would ignore it, because you didn't change anything in .spec file

**Comment by marusak** [comment]
> Some cockpit tests are still failing. Is it expected behavior? Do you want to fix it in another PR?

There is some issue with insights. @pinotree said he will take over

**Comment by marusak** [comment]
I've retried with a new image and now it fails differently:
```
TypeError: I.GetOrg is not a function
```

**Comment by marusak** [comment]
Seems like it was introduced in 40e4018b5f788e169a2bc87416b629ec380e6023 by @jirihnidek 
Any idea why it fails?

**Comment by jirihnidek** [comment]
> Seems like it was introduced in [40e4018](https://github.com/candlepin/subscription-manager/commit/40e4018b5f788e169a2bc87416b629ec380e6023) by @jirihnidek
> Any idea why it fails on rhel-9?

It is simple the rhel-9 still contain old rhsm.service without support of `GetOrg()` D-Bus method. If you want to test the this plugin properly, then you have to stop rhsm.service provided by rhel-9 and use fresh rhsm.service from PR. I thought that rhsm_service from PR is already used to be able to test new D-Bus API provided by rhsm.service. Maybe it is different for rhel-9.

How to fix it? You can create RPMs from subscription-manager.spec provided in this repo and install to the system. You can also use following trick for running rhsm.service:

```bash
PYTHONPATH=./src python -m subscription_manager.scripts.rhsm_service --verbose
```

You have to run previous command in the root of sub-man source directory.

**Comment by marusak** [comment]
> It is simple the rhel-9 still contain old rhsm.service without support of GetOrg() D-Bus method

Seems that rhel-8-4 and 8-5 already have this? So this new version has been released into 8-4 and 8-5 but not into 9-0?

**Comment by jirihnidek** [comment]
> > It is simple the rhel-9 still contain old rhsm.service without support of GetOrg() D-Bus method
> 
> Seems that rhel-8-4 and 8-5 already have this? So this new version has been released into 8-4 and 8-5 but not into 9-0?

I don't believe that new GetOrg() has been released in any rhel. It is very new. It has been introduced in #2780 (merged to main branch 6 days ago).

**Comment by ptoscano** [comment]
Note that `integration-tests/vm.install` is supposed to build and install sub-man from sources in the testing system. Considering  #2780 worked, then a possibility is that on RHEL 9 we need to do something else to properly "install" it.
