### PR TITLE
1248821: All subs date picker was failing.

### PR DESCRIPTION
**Pull request by alikins**
DatePicker is a subclass of HBox, so self.get_parent()
doesn't make sense, so clicking on the date picker would
throw an error:

TypeError: argument parent: Expected Gtk.Window, but got
gi.overrides.Gtk.Box

### CODE REVIEW

**Comment by wottop** [comment]
The error still appears. The data picker does not work in either 7.1 or 6.7.

**Comment by alikins** [comment]
Paste the entire error? 
The line the error in 1248821 references doesn't exist anymore.

**Comment by wottop** [comment]
I stand corrected. It does work in 7.1
in 6,7 it throws the following:
Traceback (most recent call last):
  File "/usr/share/rhsm/subscription_manager/gui/widgets.py", line 726, in _button_clicked
    self._calendar_window = ga_Gtk.Window(ga_Gtk.WindowType.TOPLEVEL)
AttributeError: 'module' object has no attribute 'Window'

**Comment by wottop** [comment]
all good. ack.
